<?php
namespace grozzzny\lang\widgets;

use grozzzny\lang\models\Lang;
use yii\base\Widget;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

class WLang extends Widget
{
    public $options = [];
    private $_options = [
        'encode' => false,
    ];
    public $itemOptions = [];

    public function init()
    {
        $this->options = ArrayHelper::merge($this->_options, $this->options);
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run() {

        $arr = [];

        foreach (Lang::find()->all() as $lang){
            $options = $this->itemOptions;

            if(Lang::getCurrent()->id == $lang->id) $options['class'] = $options['class'] . ' active';

            $arr[] = Html::a($lang->name, $lang->link, $options);
        }

        return Html::ul($arr, $this->options);
    }
}